n = input('Digite algo: ')
print(type(n))
print('É alfanumérico?', n.isalnum())
print('É minúsculo?', n.islower())
print('É numérico?', n.isnumeric())
print('É maiusculo?', n.isupper())
print('É apenas letra?', n.isalpha())
print('É decimal?', n.isdecimal())
print('É um espaço?', n.isspace())
print('É uma palavra iniciada com maiuscula?', n.istitle())
